name: blue_fire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^2.2.0
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.4.0
  permission_handler: ^10.2.0
  flutter_blue: ^0.8.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - lib/assets/lottie/
    - lib/assets/images/

